chat_commerce/urls.py
from django.urls import path

from . import views, viewAcceptOffer

app_name = 'chat_commerce'

urlpatterns = [
    path('', views.RequestListView.as_view(), name='request_list'),
    path('offered_to_you/', views.OfferedToYou_ListView.as_view(), name='offerred_to_you'),
    path('your_offers/', views.YourOffers_ListView.as_view(), name='your_offers'),
    path('accept_offer/<int:offerId>/', viewAcceptOffer.accept_offer, name='accept_offer'),
    path('make_offer/<int:id>/', views.OfferCreateView.as_view(), name='make_offer'),
    path('make_request/', views.RequestCreateView.as_view(), name='make_request'),
    path('delete_request/<pk>', views.RequestDeleteView.as_view(), name='delete_request'),
    path('delete_offer/<pk>', views.OfferDeleteView.as_view(), name='delete_offer'),
    path('offer_update/<pk>', views.OfferUpdateView.as_view(), name='offer_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat_commerce.urls', namespace='chat_commerce')),
]

chat_commerce/models.py
from django.db import models
from django.contrib.auth.models import User


class Request(models.Model):
    User = models.ForeignKey(User, related_name='requesting_user', on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    accepted = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Requests'
        ordering = ('date', "start_time", "end_time")

    def __str__(self):
        return f"{self.User.username.capitalize()}, {self.date}, at {self.start_time}"


class Offer(models.Model):
    User = models.ForeignKey(User, related_name='offering_user', on_delete=models.CASCADE)
    Request = models.ForeignKey(Request, related_name='original_request', on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    accepted = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Offerings'
        ordering = ('date', "start_time", "end_time")

    def __str__(self):
        return f"{self.User.username}, {self.date}, at {self.start_time}"

chat_commerce/views.py
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django import forms
from django.contrib import messages


from .models import Request, Offer


class RequestListView(ListView):
    model = Request
    template_name = 'chat_commerce/request_list.html'
    raise_exception = True


class OfferedToYou_ListView(LoginRequiredMixin, ListView):
    model = Offer
    template_name = 'chat_commerce/offered_to_you_list.html'
    raise_exception = True

    def get_queryset(self):
        request_ids = Request.objects.filter(User=self.request.user).values_list('pk', flat=True)
        print(request_ids)
        return Offer.objects.filter(Request_id__in=request_ids)


class YourOffers_ListView(LoginRequiredMixin, ListView):
    model = Offer
    template_name = 'chat_commerce/your_offers.html'
    raise_exception = True

    def get_queryset(self):
        return Offer.objects.filter(User=self.request.user)


class OfferCreateView(LoginRequiredMixin, CreateView):
    model = Offer
    fields = ['date', 'start_time', 'end_time', 'message']
    template_name = 'chat_commerce/offer_create.html'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        form = super(OfferCreateView, self).get_form(form_class)
        form.fields['date'].widget = forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'})
        form.fields['start_time'].widget = forms.TextInput(attrs={'placeholder': 'HH:MM:SS'})
        form.fields['end_time'].widget = forms.TextInput(attrs={'placeholder': 'HH:MM:SS'})
        form.fields['message'].widget = forms.TextInput(attrs={'placeholder': 'Enter a message'})
        return form
    
    def form_valid(self, form):
        form.instance.User = self.request.user
        form.instance.Request = Request.objects.get(pk=self.kwargs['id'])
        form.instance.active = True
        form.save()
        messages.success(self.request, 'Your offer has been sent successfully!')
        return redirect(reverse_lazy('chat_commerce:your_offers'))


class RequestCreateView(LoginRequiredMixin, CreateView):
    model = Request
    fields = ['date', 'start_time', 'end_time', 'message']
    template_name = 'chat_commerce/request_create.html'

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        form = super(RequestCreateView, self).get_form(form_class)
        form.fields['date'].widget = forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'})
        form.fields['start_time'].widget = forms.TextInput(attrs={'placeholder': 'HH:MM:SS'})
        form.fields['end_time'].widget = forms.TextInput(attrs={'placeholder': 'HH:MM:SS'})
        form.fields['message'].widget = forms.TextInput(attrs={'placeholder': 'Enter a message'})
        return form
    
    def form_valid(self, form):
        form.instance.User = self.request.user
        form.instance.active = True
        form.save()
        messages.success(self.request, 'Your request has been created successfully!')
        return redirect(reverse_lazy('chat_commerce:request_list'))


class RequestDeleteView(LoginRequiredMixin, DeleteView):
    model = Request
    template_name = 'chat_commerce/delete_request.html'
    success_url = reverse_lazy('chat_commerce:request_list')

    def form_valid(self, form):
        self.object = self.get_object()
        self.object.delete()
        messages.success(self.request, 'Your request has been deleted successfully!')
        return redirect(reverse_lazy('chat_commerce:request_list'))
    

class OfferDeleteView(LoginRequiredMixin, DeleteView):
    model = Offer
    template_name = 'chat_commerce/delete_offer.html'
    success_url = reverse_lazy('chat_commerce:your_offers')

    def form_valid(self, form):
        self.object = self.get_object()
        self.object.delete()
        messages.success(self.request, 'Your offer has been deleted successfully!')
        return redirect(reverse_lazy('chat_commerce:your_offers'))
    


class OfferUpdateView(LoginRequiredMixin, UpdateView):
    model = Offer
    fields = ['date', 'start_time', 'end_time', 'message']
    template_name = 'chat_commerce/offer_update.html'
    
    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Your offer has been updated successfully!')
        return redirect(reverse_lazy('chat_commerce:your_offers'))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Fintual Chat Market{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>

<body>
	<header>
	        <nav class="navbar navbar-expand-md navbar-dark bg-primary border-bottom">
	            <div class="container-fluid">
	                <a class="navbar-brand" href="{% url "chat_commerce:request_list" %}">Available swaps</a>
	                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
	                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
	                    <span class="navbar-toggler-icon"></span>
	                </button>
	                <div class="collapse navbar-collapse" id="navbarCollapse">
	                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
							<li class="nav-item active">
	                            <a class="nav-link active" aria-current="page" href="{% url "chat_commerce:offerred_to_you" %}">Offered to you</a>
	                        </li>
							<li class="nav-item active">
	                            <a class="nav-link active" aria-current="page" href="{% url "chat_commerce:your_offers" %}">Your offers</a>
	                        </li>
	                    </ul>
	                </div>
	            </div>
	        </nav>
	    </header>
	<div id="content">{% block content %} {% endblock %}</div>
</body>
</html>	

templates/chat_commerce/delete_offer.html
{% extends "../base.html" %}

{% block title %}

Delete request

{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}

    {{ form.as_p }}
    
    <h4 class="display-7 fw-bold">Do you wish to delete the following offer?</h4>
    
    <h4 class="display-7">{{ offer }}</h4>

    <input type="submit" value="Delete">
</form>

{% endblock %}

templates/chat_commerce/delete_request.html
{% extends "../base.html" %}

{% block title %}

Delete request

{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}

    {{ form.as_p }}
    
    <h4 class="display-7 fw-bold">Do you wish to delete the following request?</h4>
    
    <h4 class="display-7">{{ request }}</h4>

    <input type="submit" value="Delete">
</form>

{% endblock %}

templates/chat_commerce/offer_create.html
{% extends "../base.html" %}

{% block title %}

Send Offer

{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

templates/chat_commerce/offer_list.html
{% extends "../base.html" %}

{% block title %}

List of offerings

{% endblock %}

{% block content %}
	
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">Date</th>
	      <th scope="col">Starting Time</th>
	      <th scope="col">Ending Time</th>
          <th scope="col">User</th>
          <th scope="col">To User</th>
		  <th scope="col">Message</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for offer in object_list %}
        {% if offer.active %}
		<tr>
	      <td>{{offer.date}}</td>
	      <td>{{offer.start_time}}</td>
	      <td>{{offer.end_time}}</td>
          <td>{{offer.User.username}}</td>
          <td>{{offer.Request.User.username}}</td>
		  <td>{{offer.message}}</td>
		  <td>
			<a button type="button" class="btn btn-outline-secondary btn-sm" href="{% url 'chat_commerce:accept_offer' %}">Accept</a>
		  </td>
	    </tr>
        {% endif %}
	   {% endfor %}
	  </tbody>
	</table>
	
{% endblock %}

templates/chat_commerce/offer_update.html
{% extends "../base.html" %}

{% block title %}

Update your offer

{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

templates/chat_commerce/offered_to_you_list.html
{% extends "../base.html" %}

{% block title %}

Fintual's Chat Market

{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
		{{ message }}
	  </div>
    {% endfor %}
</ul>
{% endif %}

	<div class="px-6 py-2 my-2 text-center">
		<h1 class="display-5 fw-bold">List of swaps offered to you</h1>
	</div>

	<table class="table">
	  <thead>
	    <tr>
		  <th scope="col">Your request</th>
	      <th scope="col">Offered Date</th>
	      <th scope="col">Offered Starting Time</th>
	      <th scope="col">Offered Ending Time</th>
          <th scope="col">Offered by</th>
		  <th scope="col">Message</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for offer in object_list %}
        {% if offer.active %}
		<tr>
		  <td>{{offer.Request}}</td>
	      <td>{{offer.date}}</td>
	      <td>{{offer.start_time}}</td>
	      <td>{{offer.end_time}}</td>
          <td>{{offer.User.username}}</td>
		  <td>{{offer.message}}</td>
		  <td>
			<a button type="button" class="btn btn-outline-secondary btn-sm" href="{% url 'chat_commerce:accept_offer' offerId=offer.id %}">Accept</a>
		  </td>
	    </tr>
        {% endif %}
	   {% endfor %}
	  </tbody>
	</table>
	
{% endblock %}

templates/chat_commerce/request_create.html
{% extends "../base.html" %}

{% block title %}

Make your request

{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    
    <input type="submit" value="Save">

</form>


{% endblock %}

templates/chat_commerce/request_list.html
{% extends "../base.html" %}

{% block title %}

Fintual's Chat Market

{% endblock %}

{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
	<div class="alert alert-success" role="alert">
		{{ message }}
	  </div>
    {% endfor %}
</ul>
{% endif %}
	
	<div class="px-6 py-2 my-2 text-center">
		<h1 class="display-5 fw-bold">Bulletin board</h1>
		<h3 class="display-7 fw-bold">List of all available swaps</h3>
	</div>

	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">Date</th>
	      <th scope="col">Starting Time</th>
	      <th scope="col">Ending Time</th>
          <th scope="col">User</th>
		  <th scope="col">Message</th>
		  <th scope="col">Trade</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for request in object_list %}
        {% if request.active %}
		<tr>
	      <td>{{request.date}}</td>
	      <td>{{request.start_time}}</td>
		  <td>{{request.end_time}}</td>
          <td>{{request.User.username}}</td>
		  <td>{{request.message}}</td>
		  <td>
			  {% if user != request.User %}
			<a button type="button" class="btn btn-outline-primary btn-sm" href="{% url 'chat_commerce:make_offer' request.id %}">Make an offer</a>
			  {% else %}
			<a button type="button" class="btn btn-outline-secondary btn-sm" href="{% url 'chat_commerce:delete_request' request.id %}">Delete request</a>
			  {% endif %}
		  </td>
	    </tr>
		
        {% endif %}
	   {% endfor %}
	   
	  </tbody>
	</table>
	<div class="d-grid gap-2 col-6 mx-auto"">
		<a button class="btn btn-primary" type="button" href="{% url 'chat_commerce:make_request' %}">Add your request</a>
	  </div>
{% endblock %}

templates/chat_commerce/your_offers.html
{% extends "../base.html" %}

{% block title %}

List of offerings

{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
		{{ message }}
	  </div>
    {% endfor %}
</ul>
{% endif %}

	<div class="px-6 py-2 my-2 text-center">
		<h1 class="display-5 fw-bold">List of swaps offered by you</h1>
	</div>

	<table class="table">
	  <thead>
	    <tr>
		  <th scope="col">Original request</th>
		  <th scope="col">Original message</th>
	      <th scope="col">Your Date</th>
	      <th scope="col">Your Starting Time</th>
	      <th scope="col">Your Ending Time</th>
		  <th scope="col">Your message</th>
	    </tr>
	  </thead>
	  <tbody>
	    {% for offer in object_list %}
        {% if offer.active %}
		<tr>
		  <td>{{offer.Request}}</td>
          <td>{{offer.Request.message}}</td>
	      <td>{{offer.date}}</td>
	      <td>{{offer.start_time}}</td>
	      <td>{{offer.end_time}}</td>
		  <td>{{offer.message}}</td>
		  <td>
			<a button type="button" class="btn btn-outline-primary btn-sm" href="{% url 'chat_commerce:offer_update' offer.id %}">Edit</a>
		  </td>
		  <td>
			<a button type="button" class="btn btn-outline-secondary btn-sm" href="{% url 'chat_commerce:delete_offer' offer.id %}">Delete</a>
		  </td>
	    </tr>
        {% endif %}
	   {% endfor %}
	  </tbody>
	</table>
	
{% endblock %}